# Generated by Django 4.1.4 on 2023-01-16 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recipeient',
            new_name='recipient',
        ),
    ]
